// Generated by CoffeeScript 1.8.0
(function() {
  var app, bodyParser, compression, errorHandler, express, logger, methodOverride, multer, path;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  methodOverride = require('method-override');

  bodyParser = require('body-parser');

  multer = require('multer');

  errorHandler = require('errorhandler');

  compression = require("compression");

  app = express();

  app.use(logger('dev'));

  app.use(methodOverride());

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(multer());

  app.use(compression());

  if ('development' === app.get('env')) {
    app.use(errorHandler());
  }

  module.exports = {
    express: express,
    initAppFunc: function(app, express) {},
    launch: function(port, host, postLaunchCb) {
      app.set('port', port);
      module.exports.initAppFunc(app, express);
      return app.listen(port, host, function() {
        console.log('Express server listening on port ' + port);
        if (postLaunchCb) {
          return postLaunchCb();
        }
      });
    },
    launchLocalDev: function(postLaunchCb) {
      var findport, open;
      findport = require("find-free-port");
      open = require("open");
      return findport(10000, 10100, '127.0.0.1', function(err, port) {
        return module.exports.launch(port, '127.0.0.1', function() {
          console.log("Launching browser window");
          return open("http://localhost:" + port);
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=index.js.map
